DefaultContentLanguage = "ja"
baseURL = "https://www.sigmact.com/updated"
theme = "dot-hugo-documentation-theme"
enableRobotsTXT = true
enableGitInfo = true

RelativeURLs=true
CanonifyURLs=true

# HTMLを生成するディレクトリ
publishDir = "public/production"
# Google analytics
googleAnalytics = "UA-139325091-1"

[params]
  articleToCLevel = 1

[blackfriday]
  hrefTargetBlank = true

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = true
    startLevel = 2

[Languages]

  # Japanese Language
  [Languages.ja]
  languageName = "ja"
  weight = 1
  languageCode = "ja-JP"
  title = "SIGMA UPDATED"
  dateFormat = "2006 January 2"
  home = "企業サイトへ"
  logo = "SIGMA UPDATED"
  copyright = "Sigma Consulting Co.,Ltd. All rights reserved."
  blobURL = "https://sigmactwwwupdated.z11.web.core.windows.net/"

    # navigation
    [Languages.ja.menu]
            
        
      [[Languages.ja.menu.main]]
        weight = 2
        name = "カテゴリ"
        url = "pages"
        hasChildren = true

          [[Languages.ja.menu.main]]
          parent = "カテゴリ"
          name = "Azure"
          url = "azure"
          weight = 1

          [[Languages.ja.menu.main]]
          parent = "カテゴリ"
          name = "DevOps"
          url = "devops"
          weight = 2

          [[Languages.ja.menu.main]]
          parent = "カテゴリ"
          name = "デザイン"
          url = "design"
          weight = 3

          [[Languages.ja.menu.main]]
          parent = "カテゴリ"
          name = "マネジメント"
          url = "management"
          weight = 4

           [[Languages.ja.menu.main]]
          parent = "カテゴリ"
          name = "インタビュー"
          url = "interview"
          weight = 5




    # banner
    [Languages.ja.params.banner]
      title = "SIGMA UPDATED"
      description = "このサイトでは、シグマコンサルティングで突き詰めている、Azure、DevOps(開発、運用)、デザイン、マネジメント、文化等の情報を「更新(UPDATE)」してお伝えします。"
      image = "images/hero.jpg"
      placeholder = ""

    # Topics
    [Languages.ja.params.topics]
      title = "記事一覧"
    
    # call to action
    [Languages.ja.params.cta]
      enable = true
      title = "是非一緒にお話ししてみませんか？"
      description = "Azureのこと、ECのこと、DevOpsのこと、デザインのこと、PMのこと、話し合ってみませんか？"
      btnText = "お問い合わせ"
      btnURL = "どこに飛ばすか考え中"

    # contact
    [Languages.ja.params.contact]
      title = "Got Any Questions"
      content = "Submit the form and confirm your email address at <a class='text-primary' href='https://formspree.io/'>Formspree</a> Then add the following lines to contact page YAML Front Matter."

    # footer social icon
    [[Languages.ja.socialIcon]]
      icon = "fab fa-facebook"
      linkURL = "https://www.facebook.com/sigmact/"
            
    [[Languages.ja.socialIcon]]
      icon = "fab fa-instagram"
      linkURL = "https://www.instagram.com/sigmaconsulting/"
